[project]
name = 'lamp_contrants'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.archive_with_notification]
path = 'contracts/archive_with_notification.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_sharing_rewards]
path = 'contracts/file_sharing_rewards.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_send_with_refund_on_failure]
path = 'contracts/multi_send_with_refund_on_failure.clar'
clarity_version = 2
epoch = 2.5

[contracts.reward_distribytion]
path = 'contracts/reward_distribytion.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_access_control_list]
path = 'contracts/storage_with_access_control_list.clar'
clarity_version = 2
epoch = 2.5

[contracts.withdrawal_fee_wallet]
path = 'contracts/withdrawal_fee_wallet.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
